### ISSUE TITLE
Question: How to deal with large source results

### ISSUE THREAD

**Issue by frascuchon** [obsei/obsei#204]
First of all, congratulation for this awesome open-source tool. It's quite easy to use and very intuitive.

I'm working with twitter source observer with recent searches and I plan to use the full-archive tweets search.

In that case, I imagine the twitter source will fetch a huge amount of data before start analysis or even sink phase.

My question is if there is any way of source response batching or streaming in order to perform partials workflows.

Thanks in advance!

**Comment by lalitpagaria** [comment]
Thank you @frascuchon 

> I'm working with twitter source observer with recent searches and I plan to use the full-archive tweets search.

Not sure how you able to fetch full-archive tweet search as currently twitter only providing this capability for academic purpose only. Please check this link out https://developer.twitter.com/en/docs/twitter-api/tweets/search/introduction
Otherwise you might need to take Enterprise plan refer https://developer.twitter.com/en/docs/twitter-api/enterprise/search-api/overview
Currently I have tested Obsei for v2 (which is in early access phase) not on v1.1 version Refer https://github.com/twitterdev/search-tweets-python . But eventually they going to replace everything with v2 version.

> In that case, I imagine the twitter source will fetch a huge amount of data before start analysis or even sink phase
>
> My question is if there is any way of source response batching or streaming in order to perform partials work

I thought about this scenario, so created [this issue](https://github.com/obsei/obsei/issues/145) to have batching and more advanced capabilities. In cloud hosted Obsei currently I am using kafka streaming for this purpose.
I can suggest two ways -
1. Simple way (also you able to hadle twitter rate limit 300 tweets per 15 min): As each observer have state management capability (refer example https://github.com/obsei/obsei/blob/master/example/with_state_example.py). So it would be better if you run Twitter Observer frequently with smaller manageable number (control it via `max_tweets` param, twitter impose max limit which is 100) along with enabling state management via any of your preferred DB (sqlite, mysql, postgres etc). You will not received duplicate tweet data with state management and twitter api always fetch newer tweets with ids greater than previous run (this param in code https://github.com/obsei/obsei/blob/master/obsei/source/twitter_source.py#L228)
2. Complex way: If you going to deploy each nodes (observer, analyzer and informer) in separate container then you can add any of streaming/queuing capability (we planned about adding [kafka support](https://github.com/obsei/obsei/issues/126) but it will not be delivered sooner) in between to handle batching.

Please let me know if this help.

**Comment by lalitpagaria** [comment]
Added comments to https://github.com/obsei/obsei/blob/master/example/with_state_example.py so it become easier to understand state management. Ideally it should be documented properly, I put this in backlog.

**Comment by frascuchon** [comment]
Thanks @lalitpagaria 

I've seen that obsei works with twitter v2 endpoints. So, once the premium plan will be upgrade to v2 endpoints, I will check the simple way that you suggest. I think is quite enough for our use case.

Thanks a lot!
